const SUPABASE_URL='https://agczzdjxnytjzgprvcxq.supabase.co';
const SUPABASE_KEY='sb_publishable_0Sn8fs22OGVbNdvyZMILHA_Vv9NI2BE';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={session:null,leads:[],clients:[],projects:[],files:[],active:'dashboard',editing:null};
const labels={dashboard:'Overview',leads:'Requests',clients:'Clients',projects:'Projects',files:'Files'};
const schemas={
 leads:[['name','Full name','text',true],['phone','Phone','tel',true],['email','Email','email'],['address','Project address','text'],['service','Service','select',['Concrete','Grading','Excavation','Pavers','Landscaping','Remodeling','Other']],['status','Status','select',['new','contacted','estimate_scheduled','quoted','won','lost']],['estimated_value','Estimated value','number'],['message','Project details','textarea']],
 clients:[['name','Client name','text',true],['phone','Phone','tel'],['email','Email','email'],['address','Address','text'],['notes','Notes','textarea']],
 projects:[['name','Project name','text',true],['client_id','Client','client'],['service','Service','select',['Concrete','Grading','Excavation','Pavers','Landscaping','Remodeling','Other']],['status','Status','select',['planning','scheduled','in_progress','on_hold','completed','cancelled']],['address','Jobsite address','text'],['start_date','Start date','date'],['end_date','End date','date'],['contract_value','Contract value','number'],['notes','Project notes','textarea']]
};
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.className=`toast show${error?' error':''}`;clearTimeout(el._t);el._t=setTimeout(()=>el.className='toast',3500)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)||0)}
async function boot(){const{data:{session}}=await db.auth.getSession();setSession(session);db.auth.onAuthStateChange((_e,s)=>setSession(s));}
async function setSession(session){state.session=session;$('#auth-view').classList.toggle('hidden',!!session);$('#app-view').classList.toggle('hidden',!session);if(session){$('#user-email').textContent=session.user.email;await refresh();}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const email=$('#login-email').value.trim(),password=$('#login-password').value;const{error}=await db.auth.signInWithPassword({email,password});if(error)toast(error.message,true);});
$('#logout-btn').addEventListener('click',()=>db.auth.signOut());
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
function showView(name){state.active=name;$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));$$('.sidebar nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#page-title').textContent=labels[name];$('#new-record-btn').style.display=['leads','clients','projects'].includes(name)?'inline-flex':'none';}
async function refresh(){const [leads,clients,projects,files]=await Promise.all([
 db.from('leads').select('*').order('created_at',{ascending:false}),db.from('clients').select('*').order('created_at',{ascending:false}),db.from('projects').select('*,clients(name)').order('created_at',{ascending:false}),db.from('project_files').select('*,projects(name)').order('created_at',{ascending:false})]);
 for(const r of [leads,clients,projects,files])if(r.error){toast(r.error.message,true);return;}
 state.leads=leads.data||[];state.clients=clients.data||[];state.projects=projects.data||[];state.files=files.data||[];renderAll();}
function renderAll(){renderDashboard();renderTable('leads');renderTable('clients');renderTable('projects');renderFiles();fillProjectSelect();}
function renderDashboard(){const open=state.leads.filter(x=>!['won','lost'].includes(x.status));const active=state.projects.filter(x=>!['completed','cancelled'].includes(x.status));$('#metric-leads').textContent=open.length;$('#metric-projects').textContent=active.length;$('#metric-clients').textContent=state.clients.length;$('#metric-value').textContent=money(state.leads.reduce((a,x)=>a+(Number(x.estimated_value)||0),0));$('#recent-leads').innerHTML=listItems(open.slice(0,5),'lead');$('#recent-projects').innerHTML=listItems(active.slice(0,5),'project');}
function listItems(items,type){if(!items.length)return'<div class="empty">Nothing here yet.</div>';return items.map(x=>`<div class="list-item"><div><strong>${esc(x.name)}</strong><span>${esc(type==='lead'?`${x.service||'General'} · ${x.phone||''}`:`${x.service||'Project'} · ${x.clients?.name||'No client'}`)}</span></div><span class="badge">${esc((x.status||'new').replaceAll('_',' '))}</span></div>`).join('')}
function getFiltered(type){let rows=state[type];const q=$(`#${type.slice(0,-1)}-search`)?.value.toLowerCase()||'';const status=$(`#${type.slice(0,-1)}-filter`)?.value||'';return rows.filter(x=>{const hay=JSON.stringify(x).toLowerCase();return(!q||hay.includes(q))&&(!status||x.status===status)})}
function renderTable(type){const rows=getFiltered(type),target=$(`#${type.slice(0,-1)}-list`);if(!target)return;if(!rows.length){target.innerHTML='<div class="empty">No records found.</div>';return;}const cols=type==='leads'?['name','phone','service','status','estimated_value','created_at']:type==='clients'?['name','phone','email','address','created_at']:['name','client','service','status','contract_value','start_date'];target.innerHTML=`<table class="data-table"><thead><tr>${cols.map(c=>`<th>${c.replaceAll('_',' ')}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${cell(type,r,c)}</td>`).join('')}<td class="row-actions"><button onclick="editRecord('${type}','${r.id}')">Edit</button><button onclick="deleteRecord('${type}','${r.id}')">Delete</button></td></tr>`).join('')}</tbody></table>`;}
function cell(type,r,c){if(c==='status')return`<span class="badge">${esc((r[c]||'').replaceAll('_',' '))}</span>`;if(c.includes('value'))return money(r[c]);if(c==='created_at'||c.endsWith('_date'))return r[c]?new Date(r[c]).toLocaleDateString():'—';if(c==='client')return esc(r.clients?.name||'—');return esc(r[c]||'—')}
['lead-search','lead-filter','client-search','project-search','project-filter'].forEach(id=>$(`#${id}`)?.addEventListener('input',()=>renderTable(id.startsWith('lead')?'leads':id.startsWith('client')?'clients':'projects')));
$('#new-record-btn').addEventListener('click',()=>openDialog(state.active));
window.editRecord=(type,id)=>openDialog(type,state[type].find(x=>x.id===id));
function openDialog(type,row=null){state.editing={type,row};$('#dialog-title').textContent=`${row?'Edit':'New'} ${type.slice(0,-1)}`;$('#record-fields').innerHTML=schemas[type].map(f=>fieldHtml(f,row)).join('');$('#record-dialog').showModal();}
function fieldHtml([name,label,type,opt],row){const val=row?.[name]??'';const req=opt===true?'required':'';if(type==='textarea')return`<label class="wide">${label}<textarea name="${name}">${esc(val)}</textarea></label>`;if(type==='select')return`<label>${label}<select name="${name}">${opt.map(o=>`<option value="${o}" ${val===o?'selected':''}>${o.replaceAll('_',' ')}</option>`).join('')}</select></label>`;if(type==='client')return`<label>${label}<select name="${name}"><option value="">No client</option>${state.clients.map(c=>`<option value="${c.id}" ${val===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>`;return`<label class="${name==='address'?'wide':''}">${label}<input name="${name}" type="${type}" value="${esc(val)}" ${req}></label>`}
$('#record-form').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const{type,row}=state.editing;const data=Object.fromEntries(new FormData(e.currentTarget));['estimated_value','contract_value'].forEach(k=>{if(k in data)data[k]=data[k]?Number(data[k]):null});const q=row?db.from(type).update(data).eq('id',row.id):db.from(type).insert(data);const{error}=await q;if(error)return toast(error.message,true);$('#record-dialog').close();toast('Saved');await refresh();});
window.deleteRecord=async(type,id)=>{if(!confirm('Delete this record?'))return;const{error}=await db.from(type).delete().eq('id',id);if(error)return toast(error.message,true);toast('Deleted');await refresh();};
function fillProjectSelect(){$('#file-project').innerHTML='<option value="">General / no project</option>'+state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}
$('#file-form').addEventListener('submit',async e=>{e.preventDefault();const files=[...$('#file-input').files],projectId=$('#file-project').value||null;for(const file of files){const path=`${state.session.user.id}/${projectId||'general'}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await db.storage.from('project-files').upload(path,file);if(up.error){toast(up.error.message,true);continue;}const meta=await db.from('project_files').insert({project_id:projectId,file_name:file.name,storage_path:path,mime_type:file.type,size_bytes:file.size});if(meta.error)toast(meta.error.message,true);}e.currentTarget.reset();toast('Upload complete');await refresh();});
async function renderFiles(){const target=$('#file-list');if(!state.files.length){target.innerHTML='<div class="empty">No files uploaded.</div>';return;}target.innerHTML=(await Promise.all(state.files.map(async f=>{const{data}=await db.storage.from('project-files').createSignedUrl(f.storage_path,3600);return`<article class="file-card"><a href="${data?.signedUrl||'#'}" target="_blank" rel="noopener">${esc(f.file_name)}</a><small>${esc(f.projects?.name||'General')} · ${Math.round((f.size_bytes||0)/1024)} KB</small></article>`}))).join('')}
boot();